version: 0.2

env:
  variables:
    # SOURCE_VERSION: $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
    # REPO_NAME: "https://github.com/tkazusa/ml-traning-pipeline-with-ci"
    SRC: pipeline.py

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      # Build Docker images and push to ECR
      - python $SRC